widRent/recommendations/urls.py
from django.conf.urls import url
from .views import user, item, rented, basket


app_name = 'recom'

urlpatterns = [
    url(r'^$', user, name='user'),
    url(r'^item/$', item, name='item'),
    url(r'^rented/$', rented, name='rented'),
    url(r'^basket/$', basket, name='basket'),
]

widRent/widRent/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('widgets.urls')),
    url(r'^recommendations/', include('recommendations.urls')),
]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

widRent/recommendations/models.py
from django.db import models


class Angle(models.Model):
    angle   = models.FloatField(max_length=250, db_index=True)
    widgets = models.ManyToManyField('widgets.Widget', db_index=True, related_name='angles')

# class Angle2(models.Model):
#     angle   = models.FloatField(max_length=250, db_index=True)
#     widgets = models.ForeignKey('widgets.Widget', null=True, related_name='movieA')
#     widgets = models.ForeignKey('widgets.Widget', null=True, related_name='movieB')

widRent/recommendations/views.py
from django.shortcuts import render, redirect, get_object_or_404

from django.contrib.auth.models import User
from widgets.models import Widget, Rent, Basket
from .utils import calc_angle
from matching_settings import dislike_item, liked_item, not_rated_item, recommend_people_count

from django.db.models import Prefetch, Count

from django.db.models import Count, F, Q, Case, When, Prefetch, Value, CharField

def user(request):
    user = request.user
    if user.is_authenticated():

        user_vector = Widget.objects.get_vector_for_user(user)
        print('\n\n\n\n\n')
        print('%s - liked item'%liked_item)
        print('%s - disliked item'%dislike_item)
        print('%s - not rated item'%not_rated_item)

        print('\n\n\n\n\n')

        print(user.username + ' vector is ', user_vector)
        print('\n')

        # gets all users except current user and adds to dictionary
        angles_dict = {}

        for other_user in User.objects.exclude(id=user.id):
            vector = Widget.objects.get_vector_for_user(other_user)
            angle = calc_angle(vector, user_vector)

            if angle < 90:
                angles_dict[other_user.pk] = angle

            print(other_user.username + ' vector is ', vector)
            print(user.username + ' - ' + other_user.username ,' : ', angle)
            print('\n')


        angles_dict = sorted(angles_dict.items(), key=lambda x: (-x[1], x[0]))

        user_count = recommend_people_count if len(angles_dict) > recommend_people_count else len(angles_dict)

        user_list = [angles_dict[x][0] for x in range(user_count)]

        recommendations = Widget.objects.filter(
                    liked__in=user_list).exclude(
                        liked=user).exclude(disliked=user).distinct()

        context = {
            'instance': recommendations,
        }
        return render(request, 'recommendations/user.html', context)

    return redirect('widgets:index')


def item(request):
    user = request.user
    if user.is_authenticated():

        liked_qs = user.likes.all()

        print('\n\nliked widgets:')
        for i in liked_qs:
            print(i.title)

        print('\ndisliked widgets:')
        for i in user.dislikes.all():
            print(i.title)

        print('\n\n')
        
        if request.method == 'POST':
            if 'update' in request.POST:
                Widget.objects.update_item_to_item_matching()

        recommended_list = {}
        tried = []
        for i in liked_qs:
            print('\n The liked item: ',i)
            angle_query = i.angles.prefetch_related(Prefetch('widgets', queryset=Widget.objects.exclude(
                                        disliked=user).exclude(liked=user))).distinct()
            for j in angle_query:
                if j.widgets.all():
                    print(' similar widgets: ', j.widgets.all())
                    obj = j.widgets.first()
                    if obj.pk not in tried:
                        tried.append(obj.pk)
                        recommended_list[j.angle] = obj



        # recommended_list = sorted(recommended_list.items(), key=lambda x: (-x[0], x[1]))
        # count_of_tiems = recommend_people_count if len(recommended_list) > recommend_people_count else len(recommended_list)
        # recommended_list = recommended_list[0:count_of_tiems]

        context = {
            'instance': recommended_list.items(),
        }

        return render(request, 'recommendations/item.html', context)

    return redirect('widgets:index')




def rented(request):
    user = request.user
    if user.is_authenticated():
        instance = Widget.objects.filter(rent__user=user, rent__active=True)
        history = Rent.objects.filter(user=user, active=False)



        # .annotate(user_rating=Case(
        #                                     When(widget__liked=user,then=Value('liked')),
        #                                     When(widget__disliked=user,then=Value('disliked')),
        #                                     default=Value('Not rated'),
        #                                     output_field=CharField()
        #                                     ))




# Client.objects.annotate(
# ...     discount=Case(
# ...         When(account_type=Client.GOLD, then=Value('5%')),
# ...         When(account_type=Client.PLATINUM, then=Value('10%')),
# ...         default=Value('0%'),
# ...         output_field=CharField(),
# ...     ),

        context = {
            'instance': instance,
            'history': history
        }

        return render(request, 'recommendations/rented.html', context)

    return redirect('widgets:index')



def basket(request):
    user = request.user
    if user.is_authenticated():
        try:
            instance = user.basket.widgets.all()
        except:
            basket = Basket(user=user)
            basket.save()
            instance = {}

        if request.method == 'POST':
            for obj in instance:
                obj.rent_it(user)
                user.basket.widgets.remove(obj)


            return redirect('recom:rented')

        context = {
            'instance': instance,
        }
        return render(request, 'recommendations/basket.html', context)

widRent/recommendations/templates/recommendations/base.html
{% extends 'base.html' %}
{% block body %}
<div class="nav">

	<a href="{%url 'recom:basket'%}" class="{% block basket %}{% endblock basket %}">
		basket
	</a>


	<a href="{%url 'recom:rented'%}" class="{% block rented %}{% endblock rented %}">
		rented
	</a>

	<a href="{%url 'recom:user'%}" class="{% block recom_user %}{% endblock recom_user %}">
		User matching
	</a>
	<a href="{%url 'recom:item'%}" class="{% block recom_item %}{% endblock recom_item %}">
		Item matching
	</a>
</div>
{% block recom %}

{% endblock %}

{% endblock %}

widRent/recommendations/templates/recommendations/basket.html
{% extends 'recommendations/base.html' %}
{% block basket %}active{% endblock %}
{% block recom %}


<div class="recom">

	<h1>You basket</h1>
	<div class="widget__contaier">
		{% for obj in instance %}
		{% include 'widgets/widget.html' %}
		{% empty %}
		<p>Currently you are not renting any movies</p>
		{% endfor %}
		<div class="fake"></div>
		<div class="fake"></div>
	</div>


</div>



<form method="POST" action="">{% csrf_token %}
	<input type="submit" name="rent" value='rent'>
</form>
{% endblock %}

widRent/recommendations/templates/recommendations/item.html
{% extends 'recommendations/base.html' %}
{% block recom_item %}active{% endblock %}
{% block recom %}

<div class="recom">
	<h1>Your recommendations</h1>
	<form method="POST" action=".">
		{% csrf_token %}
		<input type="submit" name="update" value="update">
	</form>
	<div class="widget__contaier">
		{% for angle, obj in instance %}
		{% include 'widgets/widget.html' %}
		{% empty %}
		<p>Sorry we have nothing to offer for you now</p>
		{% endfor %}
		<div class="fake"></div>
		<div class="fake"></div>
	</div>

</div>
{% endblock %}

widRent/recommendations/templates/recommendations/rented.html
{% extends 'recommendations/base.html' %}
{% block rented %}active{% endblock %}
{% block recom %}


<div class="recom">
	<h1>You currently renting</h1>
	<div class="widget__contaier">
		{% for obj in instance %}
		{% include 'widgets/widget.html' %}
		{% empty %}
		<p>Currently you are not renting any movies</p>
		{% endfor %}
		<div class="fake"></div>
		<div class="fake"></div>
	</div>
	<h1>Your rent history</h1>
	<div class="history">
		{% for obj in history %}

		<div>
			<img src="obj.widget.image.url">
			<div class="title">
				title: {{obj.widget.title}}
			</div>
			<div class="title">
				taken at: {{obj.rented}}
			</div>
			<div class="title">
				returned at: {{obj.returned}}
			</div>
		</div>


		{% empty %}
		<p>You are not renting eny movies</p>
		{% endfor %}
		<div class="fake"></div>
		<div class="fake"></div>
	</div>
</div>
{% endblock %}

widRent/recommendations/templates/recommendations/user.html
{% extends 'recommendations/base.html' %}
{% block recom_user %}active{% endblock %}
{% block recom %}


<div class="recom">
	<h1>Your recommendations</h1>
	<div class="widget__contaier">
		{% for obj in instance %}
		{% include 'widgets/widget.html' %}
		{% empty %}
		<p>Sorry we have nothing to offer for you now</p>
		{% endfor %}
		<div class="fake"></div>
		<div class="fake"></div>
	</div>

</div>
{% endblock %}